"""add application model

Revision ID: 912e197417f0
Revises: 9f3f01a0383c
Create Date: 2026-09-14 00:39:00.388448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '912e197417f0'
down_revision: Union[str, Sequence[str], None] = '9f3f01a0383c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('environment', sa.Enum('DEV', 'STAGING', 'PROD', name='environmenttype'), nullable=False),
    sa.Column('status', sa.Enum('PROVISIONING', 'RUNNING', 'FAILED', name='statustype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
